add target level to Breachandler (#163)
What:
- add target level to Breachandler 

Why:
- to offer more fine grained control on what gets logged

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -18,17 +18,24 @@ jobs:
       - name: Check out code
         uses: actions/checkout@v1
   
+      # TODO: fix this, for master branch it fails
       - name: check if changes have release notes
         if: github.ref != 'refs/heads/master'
+        env:
+          GIT_BRANCH: ${{ github.ref }}
         run: |
-          ChangedFiles=`git diff --name-only origin/master`
-          echo $ChangedFiles
-          case "$ChangedFiles" in
-            *CHANGELOG.*)
-                printf "\n Thanks, your commits include update to release notes. \n";;
-            *)
-                printf "\n You should add release notes to CHANGELOG.md \n" && exit 77;;
-          esac
+          if [ "$GIT_BRANCH" == "master" ]; then
+              printf "\n $GIT_BRANCH branch, ignoring check for relese notes \n"
+          else
+              ChangedFiles=`git diff --name-only origin/master`
+              echo $ChangedFiles
+              case "$ChangedFiles" in
+                *CHANGELOG.*)
+                    printf "\n Thanks, your commits include update to release notes. \n";;
+                *)
+                    printf "\n You should add release notes to CHANGELOG.md \n" && exit 77;;
+              esac
+          fi
 
       - name: install apt and pip deps
         run: |
